import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import NevBar from "@/components/NevBar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true} className={`antialiased`}>
        {

          <NevBar />
        }
        {children}
      </body>
    </html>
  );
}
